#ifndef _VIRTUAL_ROBOT_DEFINES_H_
#define _VIRTUAL_ROBOT_DEFINES_H_

#cmakedefine VR_COLLISION_DETECTION_PQP @VR_COLLISION_DETECTION_PQP@
#define VR_TEST_OUTPUT_DIRECTORY "@VIRTUAL_ROBOT_TEST_DIR@/"


#endif /* _VIRTUAL_ROBOT_DEFINES_H_ */
