
# Setup paths, libs and external cmake files to be used for VIRTUAL_ROBOT


MESSAGE(STATUS "SETTING LIBRARY DEPENDENCIES FOR VIRTUAL ROBOT")
MESSAGE(STATUS " * VIRTUAL_ROBOT_VISUALIZATION: ${VIRTUAL_ROBOT_VISUALIZATION}")

IF (VIRTUAL_ROBOT_VISUALIZATION)
    # we need to check for Qt4
    IF(NOT "$ENV{QT_QMAKE_EXECUTABLE}" STREQUAL "")
	    MESSAGE (STATUS "USING QT-PATH from environment variable QT_QMAKE_EXECUTABLE: $ENV{QT_QMAKE_EXECUTABLE}")
	    file(TO_CMAKE_PATH "$ENV{QT_QMAKE_EXECUTABLE}" QT_QMAKE_EXECUTABLE)
	ENDIF()
    FIND_PACKAGE(Qt4 4.6.0 COMPONENTS QtOpenGL QtCore QtGui)
ENDIF()

MESSAGE(STATUS " * VIRTUAL_ROBOT_INCLUDE_DIRS: ${VIRTUAL_ROBOT_INCLUDE_DIRS}")
INCLUDE_DIRECTORIES(${VIRTUAL_ROBOT_INCLUDE_DIRS})

MESSAGE(STATUS " * VIRTUAL_ROBOT_COMPILE_FLAGS: ${VIRTUAL_ROBOT_COMPILE_FLAGS}")
ADD_DEFINITIONS( ${VIRTUAL_ROBOT_COMPILE_FLAGS} )

MESSAGE(STATUS " * VIRTUAL_ROBOT_LIBRARY_DIRS: ${VIRTUAL_ROBOT_LIBRARY_DIRS}")
LINK_DIRECTORIES( ${VIRTUAL_ROBOT_LIBRARY_DIRS} )

#MESSAGE(STATUS " * VIRTUAL_ROBOT_CMAKE_INCLUDE: ${VIRTUAL_ROBOT_CMAKE_INCLUDE}")
FOREACH(f ${VIRTUAL_ROBOT_CMAKE_INCLUDE})
    MESSAGE(STATUS " * VIRTUAL_ROBOT_CMAKE_INCLUDE: ${f}")
    INCLUDE(${f})
ENDFOREACH(f) 

